name: Frontend CI Pipeline

on:
  push:
    branches: [ main, master ]
 #removed pull request

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout repository code
        uses: actions/checkout@v4

      - name: 2. Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4' 
          extensions: mbstring, dom, curl, libxml, zip
          coverage: none

      - name: 3. Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # --- SEPARATE STEP: Regenerate Autoloader ---
        #Added dump composer
      - name: 4. Dump Composer Autoload
        run: composer dump-autoload --optimize

      - name: 5. Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 6. Cache Node Modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: 7. Install NPM Dependencies
        run: npm ci

      - name: 8. Run Linter
        run: npm run lint
        
      - name: 9. Run Production Build
        run: npm run build